### PR TITLE
Add basic CI for mingw-w64 32/64 bit

### PR DESCRIPTION
**Pull request by lazka**
This only builds things with meson and no tests are run.

Not sure if this is something you want, feedback/questions welcome.

It should make reviewing Windows specific changes easier since you know at least that it builds fine :)

### CODE REVIEW

**Comment by lazka** [comment]
Here is how it looks like: https://github.com/lazka/pkgconf/runs/1440848752

**Comment by kaniini** [comment]
It would be nice to run the testsuite as well, but this is a good starting point.

**Comment by lazka** [comment]
Thanks!

I can look into adding CI+tests using Linux if wanted.

**Comment by kaniini** [comment]
The stuff in ifupdown-ng/ifupdown-ng should be sufficient for Linux CI.  I just haven't brought it over yet.

**Pull request merged**
