### PR TITLE
Do a better job of freeing memory

### PR DESCRIPTION
**Pull request by dcbaker**
This sorts out all of the memory leaks found my the address sanitizer in the test suite. As a result of getting them all sorted out, I've enabled the address sanitizer in one test in the CI, to help keep that working.

### CODE REVIEW

**Comment by kaniini** [comment]
Can you add it to the woodpecker CI too?  I am trying to deprecate use of github for pkgconf due to, well, pick whatever scandal of the week honestly.

**Comment by kaniini** [comment]
(Also thank you for working on this!)

**Comment by dcbaker** [comment]
Added the woodpecker CI. Where is the canonical upstream these day, I can send PRs somewhere else (I'm sure I'll have more of them)

**Comment by kaniini** [comment]
I’ve been moving my projects to a personal gitea at gitea.treehouse.systems :)

**Comment by dcbaker** [comment]
I'll send my PRs there in the future :)

**Comment by dcbaker** [comment]
Migrated to gitea

**Pull request closed without merging**
