### PR TITLE
Fix search order

### LINKED ISSUE #326: Issue with PKG_CONFIG_PATH resolving past 2.0.0
Steps to reproduce:
1. Prep two hypothetical prefixes (could be a local install and the normal `/usr/lib/pkgconfig` folder)
```bash
for folder in a b; do
    mkdir -p $folder
    sed 's/PREFIX/'$folder'/' > $folder/c.pc << 'EOF'
prefix=/PREFIX
exec_prefix=${prefix}
includedir=${prefix}/include
libdir=${exec_prefix}/lib

Name: c
Description: c
Version: 1.0.0
Cflags: -I${includedir}
Libs: -L${libdir} -lc
Libs.private: -ld
EOF
done
export PKG_CONFIG_PATH="$PWD/a:$PWD/b"
```

2. run pkgconf < 2.0.0
```bash
$ pkgconf --static --libs c
-L/a/lib -lc -ld
```
3. run pkgconf >= 2.0.0
```bash
$ ./bui/pkgconf --static --libs c
-L/b/lib -lc -ld
```

Offending commit after bisecting seems to be https://github.com/pkgconf/pkgconf/commit/384ade5f316367f15da9dbf09853e06fe29bf2bf and reverting that restores pre-2.0.0 behavior, however, I am not entirely sure the motivation behind that commit, so I can't tell if reverting will break something else.

I can't submit to <https://gitea.treehouse.systems/ariadne/pkgconf> right now, as it's giving me error 500.

### PR DESCRIPTION
**Pull request by dg0yt**
Revert https://github.com/pkgconf/pkgconf/commit/384ade5f316367f15da9dbf09853e06fe29bf2bf. (Credits: @1480c1.)
Always insert `--with-path` dirs (command line) before anything else (environment, defaults).
Add tests.

Fixes #326.

### CODE REVIEW

**Comment by lazka** [comment]
Just wondering, why add new public APIs with this? This seems unrelated to the issue.

**Comment by dg0yt** [comment]
Do you propose to drop `pkgconf_client_dir_list_add` and to access `client->dir_list` directly from `main.c`?
(I guess my C++ish bias lets me avoid direct access to members.)

**Comment by dg0yt** [comment]
> to drop `pkgconf_client_dir_list_add` and to access `client->dir_list` directly from `main.c`?

Done.

**Comment by chewi** [comment]
This sadly didn't help in the [libxml2 case](https://gitlab.gnome.org/GNOME/libxml2/-/issues/602).

**Comment by vishwin** [comment]
I can confirm that reverting 384ade5 fixes what I [reported on gitea](https://gitea.treehouse.systems/ariadne/pkgconf/issues/250), which is most likely the same issue(s) reported here.

**Comment by dg0yt** [comment]
> This sadly didn't help in the [libxml2 case](https://gitlab.gnome.org/GNOME/libxml2/-/issues/602).

Understood. Remove the link to #322.

**Comment by kaniini** [comment]
Fixed by 652aff97906d7eadca6fe727b16f6511d8dbfe05

**Pull request closed without merging**
