### PR TITLE
[README.md] Soften and clarify wording

### PR DESCRIPTION
**Pull request by Olf0**
As discussed at https://github.com/pkgconf/pkgconf/pull/231#issuecomment-908689403 ff.

### CODE REVIEW

**Comment by Tachi107** [comment]
While this has been merged, it seems that the commits never hit the main branch

**Comment by kaniini** [comment]
Screen Shot 2021-12-11 at 12 56 18 PM

I don't know what branch you're talking about, but it is there.

**Comment by Tachi107** [comment]
image

I don't see the changes in the readme

**Comment by Olf0** [comment]
This is strange:
* Commit fe98e1b (7 Oct 2021) is not shown at https://github.com/pkgconf/pkgconf/commits/master
* Indeed the [README.md](https://github.com/pkgconf/pkgconf#readme) displayed is unchanged.
* Looking at commit fe98e1b, GitHub displays a warning atop of it: *This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.*

IMHO something went wrong.
@kaniini, can you please re-apply these changes, because I deleted the cloned repo with the branch in question.

**Pull request merged**
